Document: index
Title: Debian index Manual
Author: <insert document author here>
Abstract: This manual describes what index is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/index/index.sgml.gz

Format: postscript
Files: /usr/share/doc/index/index.ps.gz

Format: text
Files: /usr/share/doc/index/index.text.gz

Format: HTML
Index: /usr/share/doc/index/html/index.html
Files: /usr/share/doc/index/html/*.html
